
package:
   name: "hodl-qiskit"
   version: 1.0.1

source:
   git_url: https://github.com/at2005/hodl-qiskit.git

requirements:
   build:
      - python
      - setuptools
   run:
      - python


about:
   home: https://github.com/at2005/hodl-qiskit


