
package:
   name: "hodl_qiskit"
   version: 1.0.2

source:
   git_url: https://github.com/at2005/hodl-qiskit.git

requirements:
   build:
      - python
      - setuptools
   run:
      - python
   test:
      imports:
         - hodl-qiskit

about:
   home: https://github.com/at2005/hodl-qiskit


