
package:
   name: "hodl-qiskit"
   version: 1.0.0

source:
#   git_url: https://github.com/at2005/hodl-qiskit.git
   path: ../

requirements:
   build:
      - python
      - setuptools
   run:
      - python


about:
   home: https://github.com/at2005/hodl-qiskit


